import AIProviderService from "./ai-provider.service.js";
import Commit from "../../db/models/Commit.js";
import Tweet from "../../db/models/Tweet.js";
import AppError from "../../errors/AppError.js";
import { redisClient } from "../../config/redis.js";

class BatchTweetGeneratorService {
    constructor() {
        this.aiProvider = new AIProviderService();
        this.commitBatchSize = 3;
        this.minCommitsForTweet = 1;
        this.maxCommitLimit = 5;
        this.maxAutoDraftsPerRepoPerHour = 6;
        this.autoCommitWaitMs = 90000;
        this.autoCommitPollMs = 3000;
        this.minSingleCommitSignalLength = 40;
        this.trivialCommitMessages = new Set([
            'fix',
            'update',
            'minor changes',
            'wip',
            'test',
            'chore',
            'cleanup',
        ]);
    }

    async generateDailyTweets(userId) {
        try {
            console.log('Starting daily tweet generation', { userId });

            const unprocessedCommits = await this._fetchUnprocessedCommits(userId);
            if (unprocessedCommits.length < this.minCommitsForTweet) {
                console.log('Not enough commits to generate tweet', {
                    userId,
                    commitCount: unprocessedCommits.length,
                    minRequired: this.minCommitsForTweet,
                });

                return {
                    status: 'no_commits',
                    message: 'Not enough commits to generate a tweet',
                    commitCount: 0,
                };
            }

            const commitBatch = unprocessedCommits.slice(0, this.commitBatchSize);

            const commitContext = this._buildCommitContext(commitBatch);

            const aiResult = await this.aiProvider.generateTweet(commitContext);

            if (!aiResult) {
                console.warn('Failed to generate tweet from Gemini', {
                    userId,
                    commitCount: commitBatch.length,
                });

                return {
                    status: 'generation_failed',
                    message: 'AI failed to generate a valid tweet',
                    commitCount: commitBatch.length,
                };
            }

            const tweet = await this._saveTweet(userId, commitBatch, aiResult, commitContext, {
                isAutoGenerated: true,
                autoGenerationSource: 'daily',
            });

            console.log('Daily tweet generated successfully', {
                userId,
                tweetId: tweet._id,
                commitCount: commitBatch.length,
                tweetLength: tweet.content.length,
            });

            return {
                status: 'success',
                tweetId: tweet._id.toString(),
                content: tweet.content,
                commitCount: commitBatch.length,
                message: 'Tweet generated successfully',
            };
        } catch (error) {
            console.error('Error in daily tweet generation', {
                userId,
                message: error.message,
            });

            if (error instanceof AppError) {
                throw error;
            }
            throw new AppError(
                'Failed to generate daily tweet',
                500,
                'DAILY_TWEET_GENERATION_FAILED'
            );
        }
    }

    async generateOnDemandTweet(userId, commitIds = null) {
        try {
            console.log('Generating on-demand tweet', { userId, commitIds });

            if (commitIds && Array.isArray(commitIds)) {
                if (commitIds.length > this.maxCommitLimit) {
                    throw new AppError(
                        'Maximum 5 commits allowed per tweet',
                        400,
                        'COMMIT_LIMIT_EXCEEDED'
                    );
                }
            }

            let commits;
            if (commitIds && Array.isArray(commitIds) && commitIds.length > 0) {
                commits = await Commit.find({
                    _id: { $in: commitIds },
                    userId,
                })
                    .select('message additions deletions filesChanged timestamp url files')
                    .lean();

                if (commits.length !== commitIds.length) {
                    throw new AppError(
                        'Some commits not found or unauthorized',
                        404,
                        'BATCH_COMMITS_NOT_FOUND'
                    );
                }
            } else {
                commits = await this._fetchUnprocessedCommits(userId, 3);

                if (commits.length < this.minCommitsForTweet) {
                    return {
                        status: 'no_commits',
                        message: 'Not enough commits to generate a tweet',
                        commitCount: 0,
                    };
                }
            }

            const commitContext = this._buildCommitContext(commits);

            const aiResult = await this.aiProvider.generateTweet(commitContext);
            if (!aiResult) {
                return {
                    status: 'generation_failed',
                    message: 'AI failed to generate a valid tweet',
                    commitCount: commits.length,
                };
            }

            const tweet = await this._saveTweet(userId, commits, aiResult, commitContext, {
                isAutoGenerated: false,
                autoGenerationSource: 'manual',
            });

            console.log('On-demand tweet generated successfully', {
                userId,
                tweetId: tweet._id,
                commitCount: commits.length,
            });

            return {
                status: 'success',
                tweetId: tweet._id.toString(),
                content: tweet.content,
                commitCount: commits.length,
                message: 'Tweet generated successfully',
            };
        } catch (error) {
            console.error('Error in on-demand tweet generation', {
                userId,
                error: error.message,
            });
            if (error instanceof AppError) {
                throw error;
            }
            throw new AppError(
                'Failed to generate on-demand tweet',
                500,
                'ON_DEMAND_TWEET_GENERATION_FAILED'
            );
        }
    }

    async _fetchUnprocessedCommits(userId, limit = null) {
        const finalLimit = limit || this.commitBatchSize;

        const commits = await Commit.find({
            userId,
            isProcessed: true,
            tweeted: { $ne: true },
        })
            .select('message additions deletions filesChanged timestamp url files')
            .sort({ timestamp: -1 })
            .limit(finalLimit)
            .lean();

        return commits;
    }

    /**
     * Auto push flow:
     * waits for commit-processing jobs from the same push to finish
     * filters low-signal commits
     * applies lightweight per-repo/per-hour draft throttle
     */
    async generateAutoPushTweet(userId, repositoryId, commitShas = [], deliveryId = null) {
        try {
            if (!Array.isArray(commitShas) || commitShas.length === 0) {
                return {
                    status: 'no_commits',
                    message: 'No commits provided for auto push generation',
                    commitCount: 0,
                };
            }

            const rateLimited = await this._consumeAutoDraftRateLimit(userId, repositoryId);
            if (!rateLimited.allowed) {
                return {
                    status: 'skipped',
                    reason: 'rate_limited',
                    message: 'Auto draft skipped due to per-repository hourly limit',
                    commitCount: 0,
                };
            }

            const processedCommits = await this._waitForProcessedPushCommits(
                userId,
                repositoryId,
                commitShas
            );

            const qualityCommits = processedCommits.filter((commit) =>
                this._isMeaningfulCommitMessage(commit.message)
            );

            const combinedMessageLength = qualityCommits
                .map((c) => (c.message || '').trim().length)
                .reduce((sum, len) => sum + len, 0);

            // Avoid weak drafts from tiny/trivial pushes
            if (
                qualityCommits.length === 0 ||
                (qualityCommits.length < 2 && combinedMessageLength < this.minSingleCommitSignalLength)
            ) {
                return {
                    status: 'skipped',
                    reason: 'low_quality',
                    message: 'Auto draft skipped due to low commit signal',
                    commitCount: qualityCommits.length,
                };
            }

            const selectedCommits = qualityCommits.slice(0, this.maxCommitLimit);
            const duplicateExists = await this._hasRecentOverlappingAutoDraft(
                userId,
                selectedCommits.map((c) => c._id)
            );
            if (duplicateExists) {
                return {
                    status: 'skipped',
                    reason: 'duplicate_auto_draft',
                    message: 'Auto draft skipped due to overlapping recent draft',
                    commitCount: selectedCommits.length,
                };
            }

            const commitContext = this._buildCommitContext(selectedCommits);
            const aiResult = await this.aiProvider.generateTweet(commitContext);
            if (!aiResult) {
                return {
                    status: 'generation_failed',
                    message: 'AI failed to generate a valid auto push tweet',
                    commitCount: selectedCommits.length,
                };
            }

            const tweet = await this._saveTweet(userId, selectedCommits, aiResult, commitContext, {
                isAutoGenerated: true,
                autoGenerationSource: 'push_event',
            });

            return {
                status: 'success',
                tweetId: tweet._id.toString(),
                content: tweet.content,
                commitCount: selectedCommits.length,
                deliveryId,
            };
        } catch (error) {
            console.error('Error in auto push tweet generation', {
                userId,
                repositoryId,
                deliveryId,
                error: error.message,
            });

            if (error instanceof AppError) throw error;
            throw new AppError(
                'Failed to generate auto push draft tweet',
                500,
                'AUTO_PUSH_TWEET_GENERATION_FAILED'
            );
        }
    }

    _buildCommitContext(commits) {
        let totalAdditions = 0;
        let totalDeletions = 0;
        let totalFilesChanged = 0;

        const languageMap = {
            '.js': 'JavaScript',
            '.jsx': 'JavaScript',
            '.ts': 'TypeScript',
            '.tsx': 'TypeScript',
            '.py': 'Python',
            '.java': 'Java',
            '.cpp': 'C++',
            '.cs': 'C#',
            '.rb': 'Ruby',
            '.go': 'Go',
            '.rs': 'Rust',
            '.php': 'PHP',
            '.swift': 'Swift',
            '.kt': 'Kotlin',
            '.sql': 'SQL',
            '.html': 'HTML',
            '.css': 'CSS',
            '.json': 'JSON',
            '.md': 'Documentation',
            '.yml': 'Config',
        };

        const languages = new Set();
        const frameworks = new Set();

        const normalizedCommits = commits.map((commit) => {
            const additions = commit.additions || 0;
            const deletions = commit.deletions || 0;
            const filesChanged = commit.filesChanged || 0;

            totalAdditions += additions;
            totalDeletions += deletions;
            totalFilesChanged += filesChanged;

            const files = commit.files || [];

            files.forEach((file) => {
                const ext = file.substring(file.lastIndexOf('.')).toLowerCase();
                if (languageMap[ext]) {
                    languages.add(languageMap[ext]);
                }

                if (file.includes('react') || ext === '.jsx' || ext === '.tsx') {
                    frameworks.add('React');
                }

                if (file.includes('node') || file.includes('server') || file.includes('api')) {
                    frameworks.add('Node.js');
                }
            });

            return {
                message: commit.message,
                additions,
                deletions,
                filesChanged,
                files,
                timestamp: commit.timestamp,
                url: commit.url,
            };
        });

        const context = {
            commits: normalizedCommits,
            metadata: {
                totalAdditions,
                totalDeletions,
                totalFilesChanged,
                commitCount: commits.length,
            },
            tech: {
                languages: Array.from(languages),
                frameworks: Array.from(frameworks),
            },
            userStyle: 'professional',
        };

        return context;
    }

    async _saveTweet(userId, commits, aiResult, commitContext, options = {}) {
        const metadata = {
            commitCount: commitContext.metadata.commitCount,
            mainLanguages: commitContext.tech.languages,
        };

        const tweet = new Tweet({
            userId,
            commitIds: commits.map((c) => c._id),
            content: aiResult.content,
            status: 'draft',
            isAutoGenerated: Boolean(options.isAutoGenerated),
            autoGenerationSource: options.autoGenerationSource || 'manual',
            metadata,
            generatedAt: new Date(),
        });

        await tweet.save();
        return tweet;
    }

    async _waitForProcessedPushCommits(userId, repositoryId, commitShas) {
        const deadline = Date.now() + this.autoCommitWaitMs;
        let processed = [];

        while (Date.now() <= deadline) {
            processed = await Commit.find({
                userId,
                repositoryId,
                githubSha: { $in: commitShas },
                isProcessed: true,
                tweeted: { $ne: true },
            })
                .select('message additions deletions filesChanged timestamp url files')
                .sort({ timestamp: -1 })
                .lean();

            if (processed.length > 0) break;
            await new Promise((resolve) => setTimeout(resolve, this.autoCommitPollMs));
        }

        return processed;
    }

    async _consumeAutoDraftRateLimit(userId, repositoryId) {
        if (!redisClient?.isOpen) {
            return { allowed: true, count: 0 };
        }

        const hourBucket = new Date().toISOString().slice(0, 13);
        const key = `auto:draft:rate:${userId}:${repositoryId}:${hourBucket}`;
        const count = await redisClient.incr(key);
        if (count === 1) {
            await redisClient.expire(key, 3600);
        }

        return {
            allowed: count <= this.maxAutoDraftsPerRepoPerHour,
            count,
        };
    }

    _isMeaningfulCommitMessage(message) {
        const normalized = String(message || '').trim().toLowerCase();
        if (!normalized) return false;
        if (this.trivialCommitMessages.has(normalized)) return false;
        return normalized.length >= 6;
    }

    async _hasRecentOverlappingAutoDraft(userId, commitIds) {
        if (!commitIds.length) return false;
        const thirtyMinutesAgo = new Date(Date.now() - 30 * 60 * 1000);
        const existing = await Tweet.findOne({
            userId,
            isAutoGenerated: true,
            status: 'draft',
            createdAt: { $gte: thirtyMinutesAgo },
            commitIds: { $in: commitIds },
        })
            .select('_id')
            .lean();

        return Boolean(existing);
    }
}

export default new BatchTweetGeneratorService();