/**
 * Handles tweet fetching, polling, pagination, search, and draft actions for the dashboard and tweet history pages.
 */
import { useCallback, useEffect, useRef, useState } from 'react';
import { apiClient } from '../services/apiClient.js';

export const TWEET_MAX_LENGTH = 280;

function buildQuery(params) {
  const sp = new URLSearchParams();
  for (const [k, v] of Object.entries(params || {})) {
    if (v === undefined || v === null || v === '') continue;
    sp.set(k, String(v));
  }
  const s = sp.toString();
  return s ? `?${s}` : '';
}

function normalizeTweet(raw) {
  if (!raw) return null;
  const id = raw.id ?? raw._id;
  return {
    id: id != null ? String(id) : null,
    content: raw.content ?? '',
    status: raw.status ?? 'draft',
    metadata: raw.metadata ?? {},
    repositoryFullName: raw.repositoryFullName ?? null,
    commits: Array.isArray(raw.commits) ? raw.commits : [],
    createdAt: raw.createdAt ?? null,
    updatedAt: raw.updatedAt ?? null,
    generatedAt: raw.generatedAt ?? null,
    postedAt: raw.postedAt ?? null,
    isAutoGenerated: Boolean(raw.isAutoGenerated),
    autoGenerationSource: raw.autoGenerationSource ?? 'manual',
    raw,
  };
}

function sortTweetsNewestFirst(list) {
  return [...list].sort((a, b) => {
    const ta = new Date(a.generatedAt || a.createdAt || 0).getTime();
    const tb = new Date(b.generatedAt || b.createdAt || 0).getTime();
    return tb - ta;
  });
}

/**
 * @param {object} [options]
 * @param {number} [options.limit]
 * @param {'drafts'|'all'} [options.listScope] — drafts: status=dashboard; all: no status filter (tweet history page)
 */
export function useTweets(options = {}) {
  const limit = options.limit ?? 20;
  const listScope = options.listScope ?? 'drafts';
  const page = options.page ?? 1;
  const search = options.search ?? '';

  const [tweets, setTweets] = useState([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState(null);
  const [pagination, setPagination] = useState(null);
  const [busyTweetId, setBusyTweetId] = useState(null);
  const [actionError, setActionError] = useState(null);

  const pollTimerRef = useRef(null);
  const pollDeadlineRef = useRef(null);

  const fetchTweets = useCallback(async () => {
    setError(null);
    try {
      const queryParams = { page, limit };
      if (listScope === 'drafts') queryParams.status = 'draft';
      if (listScope === 'all' && search.trim()) queryParams.search = search.trim();
      const query = buildQuery(queryParams);
      const payload = await apiClient.get(`/api/tweets${query}`);
      const inner = payload?.data;
      const tweetsRaw = Array.isArray(inner?.tweets) ? inner.tweets : [];
      const next = sortTweetsNewestFirst(tweetsRaw.map(normalizeTweet).filter((t) => t?.id));
      setTweets(next);
      setPagination(inner?.pagination ?? null);
    } catch (e) {
      setError(e);
      setPagination(null);
    } finally {
      setLoading(false);
    }
  }, [limit, listScope, page, search]);

  useEffect(() => {
    setLoading(true);
    fetchTweets();
  }, [fetchTweets]);

  const stopPollingDrafts = useCallback(() => {
    if (pollTimerRef.current != null) {
      clearInterval(pollTimerRef.current);
      pollTimerRef.current = null;
    }
    pollDeadlineRef.current = null;
  }, []);

  /**
  * Keep requesting GET /api/tweets?status=draft at intervals until the deadline, once POST /generate returns 202.
  */
  const startPollingDrafts = useCallback(
    (pollOptions = {}) => {
      const intervalMs = pollOptions.intervalMs ?? 2000;
      const durationMs = pollOptions.durationMs ?? 60000;

      stopPollingDrafts();
      pollDeadlineRef.current = Date.now() + durationMs;

      pollTimerRef.current = setInterval(() => {
        if (pollDeadlineRef.current != null && Date.now() > pollDeadlineRef.current) {
          stopPollingDrafts();
          return;
        }
        fetchTweets();
      }, intervalMs);
    },
    [fetchTweets, stopPollingDrafts],
  );

  useEffect(() => () => stopPollingDrafts(), [stopPollingDrafts]);

  /** Draft lifecycle: persist edited text */
  const saveDraftContent = useCallback(
    async (tweetId, content) => {
      setActionError(null);
      setBusyTweetId(String(tweetId));
      try {
        await apiClient.patch(`/api/tweets/${tweetId}`, { content });
        await fetchTweets();
      } catch (e) {
        setActionError(e);
        throw e;
      } finally {
        setBusyTweetId(null);
      }
    },
    [fetchTweets],
  );

  /** Draft lifecycle: promote to approved */
  const approveDraft = useCallback(
    async (tweetId) => {
      setActionError(null);
      setBusyTweetId(String(tweetId));
      try {
        await apiClient.post(`/api/tweets/${tweetId}/approve`, {});
        await fetchTweets();
      } catch (e) {
        setActionError(e);
        throw e;
      } finally {
        setBusyTweetId(null);
      }
    },
    [fetchTweets],
  );

  /** Draft lifecycle: reject — backend resets linked commits */
  const rejectDraft = useCallback(
    async (tweetId) => {
      setActionError(null);
      setBusyTweetId(String(tweetId));
      try {
        await apiClient.post(`/api/tweets/${tweetId}/reject`, {});
        await fetchTweets();
      } catch (e) {
        setActionError(e);
        throw e;
      } finally {
        setBusyTweetId(null);
      }
    },
    [fetchTweets],
  );

  return {
    tweets,
    drafts: tweets,
    pagination,
    loading,
    error,
    refetchTweets: fetchTweets,
    refetchDrafts: fetchTweets,
    startPollingDrafts,
    stopPollingDrafts,
    saveDraftContent,
    approveDraft,
    rejectDraft,
    busyTweetId,
    actionError,
    clearActionError: () => setActionError(null),
  };
}